export { default } from "next-auth/middleware";
export const config = {
  matcher: [
    // "/addnewcustomer",
    // "/customers",
    // "/editcustomer",
    // "/editcustomer/:path*",
    // "/addnewexpense",
    // "/editexpense/:path*",
    // "/expenses",
    // "/home",
    // "/allinvoices/:path*",
    // "/editinvoice/:path*",
    // "/edititem/:path*",
    // "/createnewinvoice",
    // "/addnewitem",
    // "/invoices",
    // "/items",
    // "/addorganization",
    // "/getstarted",
    // "/manageorganization",
    // "/allreports",
    // "/expensedetails",
    // "/expensedetailsbyeachcategory",
    // "/invoicedetails",
    // "/pendingsales",
    // "/recievedpayments",
    // "/salesbycustomer",
    // "/salesbyitem",
    // "/orgprofile",
    // "/paymentsrecieved",
  ],
};
